-- Supabase schema for Logistics Startup Market
-- Includes pgvector for LLM search embeddings

-- Enable extensions
create extension if not exists pgcrypto;
create extension if not exists vector;

-- Company profiles
create table if not exists companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  domain text unique,
  website text,
  description text,
  founding_year int,
  country text,
  hq_city text,
  funding_stage text,
  status text default 'active',
  interesting boolean default false,
  logo_url text,
  profile_embedding vector(1536),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create index if not exists idx_companies_country on companies(country);
create index if not exists idx_companies_funding_stage on companies(funding_stage);
create index if not exists idx_companies_status on companies(status);

alter table if exists public.companies add column if not exists interesting boolean default false;
alter table if exists public.companies add column if not exists product_status text;
alter table if exists public.companies add column if not exists product_timeline text;
alter table if exists public.companies add column if not exists has_product boolean default false;
alter table if exists public.companies add column if not exists category text default 'Other';

create index if not exists idx_companies_category on companies(category);

-- Allow Supabase service role access to companies for server-side API queries
grant select, insert, update, delete on public.companies to service_role;

-- Categories
create table if not exists categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  parent_id uuid references categories(id) on delete set null,
  created_at timestamp with time zone default now()
);

create unique index if not exists idx_categories_name on categories(name);

-- Company-category relation
create table if not exists company_categories (
  company_id uuid references companies(id) on delete cascade,
  category_id uuid references categories(id) on delete cascade,
  primary key(company_id, category_id)
);

-- Sources for discovery
create table if not exists sources (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  url text not null,
  active boolean default true,
  last_run timestamp with time zone,
  created_at timestamp with time zone default now()
);

create unique index if not exists idx_sources_url on sources(url);

-- Raw discovery items
create table if not exists raw_items (
  id uuid primary key default gen_random_uuid(),
  source_id uuid references sources(id) on delete set null,
  url text unique,
  title text,
  content text,
  published_at timestamp with time zone,
  processed boolean default false,
  created_at timestamp with time zone default now()
);

create index if not exists idx_raw_items_processed on raw_items(processed);

-- Company updates and timeline events
create table if not exists company_updates (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references companies(id) on delete cascade,
  type text,
  title text,
  summary text,
  source_url text,
  event_date date,
  embedding vector(1536),
  created_at timestamp with time zone default now()
);

create index if not exists idx_company_updates_company_id on company_updates(company_id);
create index if not exists idx_company_updates_event_date on company_updates(event_date);

-- User profiles
create table if not exists profiles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  display_name text,
  company text,
  role text,
  created_at timestamp with time zone default now()
);

-- Follows
create table if not exists follows (
  user_id uuid references auth.users(id) on delete cascade,
  company_id uuid references companies(id) on delete cascade,
  created_at timestamp with time zone default now(),
  primary key(user_id, company_id)
);

-- Contact requests
create table if not exists contact_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  company_id uuid references companies(id) on delete cascade,
  message text,
  status text default 'open',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Premium research requests
create table if not exists premium_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  plan text not null,
  message text not null,
  status text default 'submitted',
  created_at timestamp with time zone default now()
);

create index if not exists idx_premium_requests_user_id on premium_requests(user_id);

-- Embeddings for search queries
create table if not exists query_embeddings (
  id uuid primary key default gen_random_uuid(),
  query text not null,
  embedding vector(1536) not null,
  created_at timestamp with time zone default now()
);

-- Allow Supabase service role access for the pipeline and server-side API routes
grant select, insert, update, delete on public.sources to service_role;
grant select, insert, update, delete on public.raw_items to service_role;
grant select, insert, update, delete on public.categories to service_role;
grant select, insert, update, delete on public.company_categories to service_role;
grant select, insert, update, delete on public.company_updates to service_role;
grant select, insert, update, delete on public.profiles to service_role;
grant select, insert, update, delete on public.follows to service_role;
grant select, insert, update, delete on public.contact_requests to service_role;
grant select, insert, update, delete on public.premium_requests to service_role;
grant select, insert, update, delete on public.query_embeddings to service_role;
